/* This file is generated by scripts/generate_workflow_contract.py */
/* Canonical source: apps/shared/workflow_contract.json */

export enum WorkflowNodeType {
  START = 'start',
  MESSAGE = 'message',
  OFFER_PRODUCT = 'offer_product',
  COLLECT_INFO = 'collect_info',
  CONDITION = 'condition',
  INTENT_ROUTER = 'intent_router',
  WAIT_RESPONSE = 'wait_response',
  ASSIGN_TAG = 'assign_tag',
  HANDOFF = 'handoff',
  END = 'end',
}

export enum WorkflowTriggerType {
  GREETING = 'greeting',
  INTENT = 'intent',
  KEYWORD = 'keyword',
  PRODUCT_MENTION = 'product_mention',
  ALWAYS = 'always',
}

export enum ConditionType {
  LLM = 'llm',
  EXPRESSION = 'expression',
  USER_RESPONSE = 'user_response',
}

export enum ProductOfferType {
  FREE_FIRST = 'free_first',
  PAID = 'paid',
  UPSELL = 'upsell',
}

export enum ProductSelectionType {
  SPECIFIC = 'specific',
  BY_PRICE = 'by_price',
  BY_TYPE = 'by_type',
}

export enum CollectInfoField {
  NAME = 'name',
  EMAIL = 'email',
  PHONE = 'phone',
  CUSTOM = 'custom',
}

export enum WorkflowPresetCategory {
  LEAD_CAPTURE = 'lead_capture',
  SALES = 'sales',
  HIGH_TICKET = 'high_ticket',
  SUPPORT = 'support',
}
