/* This file is generated by scripts/generate_workflow_contract.py */
/* Canonical source: apps/shared/workflow_contract.json */

export const WORKFLOW_NODE_TYPE_VALUES = ['start', 'message', 'offer_product', 'collect_info', 'condition', 'intent_router', 'wait_response', 'assign_tag', 'handoff', 'end'] as const;
export type WorkflowNodeType = (typeof WORKFLOW_NODE_TYPE_VALUES)[number];

export const WORKFLOW_TRIGGER_TYPE_VALUES = ['greeting', 'intent', 'keyword', 'product_mention', 'always'] as const;
export type WorkflowTriggerType = (typeof WORKFLOW_TRIGGER_TYPE_VALUES)[number];

export const CONDITION_TYPE_VALUES = ['llm', 'expression', 'user_response'] as const;
export type ConditionType = (typeof CONDITION_TYPE_VALUES)[number];

export const PRODUCT_OFFER_TYPE_VALUES = ['free_first', 'paid', 'upsell'] as const;
export type ProductOfferType = (typeof PRODUCT_OFFER_TYPE_VALUES)[number];

export const PRODUCT_SELECTION_TYPE_VALUES = ['specific', 'by_price', 'by_type'] as const;
export type ProductSelectionType = (typeof PRODUCT_SELECTION_TYPE_VALUES)[number];

export const COLLECT_INFO_FIELD_VALUES = ['name', 'email', 'phone', 'custom'] as const;
export type CollectInfoField = (typeof COLLECT_INFO_FIELD_VALUES)[number];

export const WORKFLOW_PRESET_CATEGORY_VALUES = ['lead_capture', 'sales', 'high_ticket', 'support'] as const;
export type WorkflowPresetCategory = (typeof WORKFLOW_PRESET_CATEGORY_VALUES)[number];
