# This file is generated by scripts/generate_workflow_contract.py
# Canonical source: apps/shared/workflow_contract.json

from __future__ import annotations

from enum import Enum

class NodeType(str, Enum):
    START = "start"
    MESSAGE = "message"
    OFFER_PRODUCT = "offer_product"
    COLLECT_INFO = "collect_info"
    CONDITION = "condition"
    INTENT_ROUTER = "intent_router"
    WAIT_RESPONSE = "wait_response"
    ASSIGN_TAG = "assign_tag"
    HANDOFF = "handoff"
    END = "end"

class TriggerType(str, Enum):
    GREETING = "greeting"
    INTENT = "intent"
    KEYWORD = "keyword"
    PRODUCT_MENTION = "product_mention"
    ALWAYS = "always"

class ConditionType(str, Enum):
    LLM = "llm"
    EXPRESSION = "expression"
    USER_RESPONSE = "user_response"

class ProductOfferType(str, Enum):
    FREE_FIRST = "free_first"
    PAID = "paid"
    UPSELL = "upsell"

class ProductSelectionType(str, Enum):
    SPECIFIC = "specific"
    BY_PRICE = "by_price"
    BY_TYPE = "by_type"

class CollectInfoField(str, Enum):
    NAME = "name"
    EMAIL = "email"
    PHONE = "phone"
    CUSTOM = "custom"

class WorkflowPresetCategory(str, Enum):
    LEAD_CAPTURE = "lead_capture"
    SALES = "sales"
    HIGH_TICKET = "high_ticket"
    SUPPORT = "support"
